### ISSUE TITLE
Error 300: Multiple Choices while downloading 1.0.9 tar.gz

### ISSUE THREAD

**Issue by abdul-imran** [Dynatrace/Dynatrace-OneAgent-Ansible#32]
We were able to download One Agent 1.0.9 using the URL https://github.com/Dynatrace/Dynatrace-OneAgent-Ansible/archive/v1.0.9.tar.gz 
But this is not working anymore. 
The error seen is 
`the given path has multiple possibilities: #<Git::Ref:0x00007fb802b2c958>, #<Git::Ref:0x00007fb802b2c390>`

We have been using ansible role to download this, can this be fixed please? Thanks.
`[0;32m    amazon-ebs: - downloading role 'OneAgent', owned by Dynatrace[0m
[0;32m    amazon-ebs: - downloading role from [https://github.com/Dynatrace/Dynatrace-OneAgent-Ansible/archive/v1.0.9.tar.gz[0m](https://github.com/Dynatrace/Dynatrace-OneAgent-Ansible/archive/v1.0.9.tar.gz%1B[0m)
[1;31m==> amazon-ebs:  [ERROR]: failed to download the file: HTTP Error 300: Multiple Choices[0m
[1;31m==> amazon-ebs: [WARNING]: - Dynatrace.OneAgent was NOT installed successfully.[0m`

The same thing works with 1.0.8. 
https://github.com/Dynatrace/Dynatrace-OneAgent-Ansible/archive/v1.0.8.tar.gz

**Comment by geofffoster** [comment]
also have this issue

**Comment by eduardocalfaia** [comment]
Hi guys,
Do you still have this issue? How was it fixed? 
Thank you

**Comment by seffparker** [comment]
Not sure it's fixed yet, but a workaround method is available ^^

**Comment by pazniak** [comment]
Workaround. I noticed that inserting `/refs/tags/` after `archive` fixes the url like so : [https://github.com/Dynatrace/Dynatrace-OneAgent-Ansible/archive/refs/tags/v1.0.9.tar.gz](https://github.com/Dynatrace/Dynatrace-OneAgent-Ansible/archive/refs/tags/v1.0.9.tar.gz)

This looks like github broke backward compatibility of their urls. Shouldn't this be fixed by github team themselves?
